/* eslint-disable */
// @ts-nocheck — generated by catalog-eject; runtime-correct but TS strict-mode false-positives on inlined catalog body
import Button from "@/components/ui/Button";
import TextAnimation from "@/components/ui/TextAnimation";
import Tag from "@/components/ui/Tag";

interface AboutTextProps {
  title: string;
  primaryButton?: { text: string; href: string };
  secondaryButton?: { text: string; href: string };
  textAnimation: "slide-up" | "fade-blur" | "fade";
}

const AboutInline = () => {
  return (
    <section aria-label="About section" className="py-12 md:py-20">
      <div className="w-content-width mx-auto">
        <div className="card p-8 md:p-12 rounded-[2rem] max-w-3xl mx-auto flex flex-col items-center text-center gap-6 shadow-lg">
          <Tag text="Built to Grow." />
          <TextAnimation
            text="About Novera"
            variant="fade-blur"
            gradientText={false}
            tag="h2"
            className="text-3xl md:text-5xl font-bold text-foreground"
          />
          <div className="flex flex-col gap-4 text-base md:text-lg text-accent text-balance leading-relaxed">
            <p>
              At Novera, we help businesses grow with modern websites and intelligent receptionists designed to attract customers, capture opportunities, and simplify communication.
            </p>
            <p>
              Your website is your first impression. Your receptionist is your connection to every customer. We build both to help your business look professional, respond faster, and never miss an opportunity.
            </p>
            <p>
              From local businesses to growing brands, Novera creates reliable solutions that save time, improve customer experiences, and help businesses move forward.
            </p>
            <p className="font-semibold text-foreground mt-2">
              Novera — The future of business.
            </p>
          </div>
        </div>
      </div>
    </section>
  );
};

export default function AboutSection() {
  return (
    <div data-webild-section="about" data-section="about" id="about">
      <AboutInline />
    </div>
  );
}
