/* eslint-disable */
// @ts-nocheck — generated by catalog-eject; runtime-correct but TS strict-mode false-positives on inlined catalog body
import { useRef, useEffect } from "react";
import gsap from "gsap";
import { ScrollTrigger } from "gsap/ScrollTrigger";
import Button from "@/components/ui/Button";

const media = [
  {
    imageSrc: "http://img.b2bpic.net/free-photo/goal-oriented-entrepreneur-luxurious-corporate-office-plans-strategy_482257-128191.jpg"
  },
  {
    imageSrc: "http://img.b2bpic.net/free-photo/general-director-using-chroma-key-template-modern-gadget_482257-124351.jpg"
  },
  {
    imageSrc: "http://img.b2bpic.net/free-photo/male-real-estate-agent-doing-business-showing-house-potential-buying-couple_23-2150164670.jpg"
  },
  {
    imageSrc: "http://img.b2bpic.net/free-photo/joyful-businesswoman-holding-tablet_74855-2024.jpg"
  },
  {
    imageSrc: "http://img.b2bpic.net/free-photo/portrait-smiling-mature-businessman-using-digital-tablet_23-2147955345.jpg"
  },
  {
    imageSrc: "http://img.b2bpic.net/free-photo/beautiful-corporate-woman-medium-shot_23-2148336873.jpg"
  }
];
const primaryButton = {
  text: "Learn More",
  href: "#contact"
};
const secondaryButton = {
  href: "#services",
  text: "View Services"
};

gsap.registerPlugin(ScrollTrigger);
import ImageOrVideo from "@/components/ui/ImageOrVideo";
import TextAnimation from "@/components/ui/TextAnimation";

type TrailMedia = { imageSrc: string; videoSrc?: never } | { videoSrc: string; imageSrc?: never };

type AboutCursorTrailProps = {
  tag: string;
  title: string;
  media: TrailMedia[];
  primaryButton: { text: string; href: string };
  secondaryButton: { text: string; href: string };
  textAnimation: "slide-up" | "fade-blur" | "fade";
};

const AboutInline = () => {
  const wrapperRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    const wrapper = wrapperRef.current;
    if (!wrapper) return;

    const mm = gsap.matchMedia();

    mm.add("(min-width: 769px)", () => {
      const images = Array.from(wrapper.querySelectorAll<HTMLElement>('[data-trail="item"]'));
      if (!images.length) return;

      let index = 0;
      let lastX = 0;
      let lastY = 0;
      let fadeTimeout: ReturnType<typeof setTimeout>;
      let isActive = false;
      const threshold = window.innerWidth / 15;

      function onMove(e: MouseEvent) {
        if (!isActive) return;
        const rect = wrapper!.getBoundingClientRect();
        const x = e.clientX - rect.left;
        const y = e.clientY - rect.top;

        // Bounds check - ignore if mouse is outside the wrapper
        if (x < 0 || y < 0 || x > rect.width || y > rect.height) return;

        if (Math.hypot(x - lastX, y - lastY) > threshold) {
          if (index >= images.length) {
            gsap.to(images[(index - images.length) % images.length], { autoAlpha: 0, scale: 0.2, duration: 2.0, ease: "expo.out" });
          }
          const img = images[index % images.length];
          gsap.set(img, { x: x - img.offsetWidth / 2, y: y - img.offsetHeight / 2, zIndex: index, force3D: true });
          gsap.fromTo(img, { autoAlpha: 0, scale: 0.8 }, { autoAlpha: 1, scale: 1, duration: 0.8, overwrite: true });

          lastX = x;
          lastY = y;
          index++;

          clearTimeout(fadeTimeout);
          fadeTimeout = setTimeout(() => images.forEach(img =>
            gsap.to(img, { autoAlpha: 0, scale: 0.2, duration: 2.0, ease: "expo.out" })
          ), 1000);
        }
      }

      function onMouseLeave() {
        clearTimeout(fadeTimeout);
        images.forEach(img =>
          gsap.to(img, { autoAlpha: 0, scale: 0.2, duration: 0.5, ease: "expo.out" })
        );
        // Reset position tracking so next entry starts fresh
        lastX = 0;
        lastY = 0;
      }

      function startTrail() {
        if (isActive || !wrapper) return;
        isActive = true;
        wrapper.addEventListener("mousemove", onMove);
        wrapper.addEventListener("mouseleave", onMouseLeave);
      }

      function stopTrail() {
        if (!isActive || !wrapper) return;
        isActive = false;
        wrapper.removeEventListener("mousemove", onMove);
        wrapper.removeEventListener("mouseleave", onMouseLeave);
        clearTimeout(fadeTimeout);
        images.forEach(img => {
          gsap.killTweensOf(img);
          gsap.set(img, { autoAlpha: 0, scale: 1 });
        });
      }

      const trigger = ScrollTrigger.create({
        trigger: wrapper,
        start: "top bottom",
        end: "bottom top",
        onEnter: startTrail,
        onEnterBack: startTrail,
        onLeave: stopTrail,
        onLeaveBack: stopTrail,
      });

      return () => {
        stopTrail();
        trigger.kill();
      };
    });

    mm.add("(max-width: 768px)", () => {
      const images = Array.from(wrapper.querySelectorAll<HTMLElement>('[data-trail="item"]'));
      if (!images.length) return;

      let index = 0;
      let lastScrollY = window.scrollY;
      let fadeTimeout: ReturnType<typeof setTimeout>;
      const threshold = 100;

      function onScroll() {
        const rect = wrapper!.getBoundingClientRect();
        if (rect.top > window.innerHeight || rect.bottom < 0) return;

        const scrollDelta = Math.abs(window.scrollY - lastScrollY);
        if (scrollDelta > threshold) {
          if (index >= images.length) {
            gsap.to(images[(index - images.length) % images.length], { autoAlpha: 0, scale: 0.2, duration: 0.8, ease: "expo.out" });
          }
          const img = images[index % images.length];
          const x = Math.random() * (rect.width - img.offsetWidth);
          const y = Math.random() * (rect.height - img.offsetHeight);
          gsap.set(img, { x, y, zIndex: index, force3D: true });
          gsap.fromTo(img, { autoAlpha: 0, scale: 0.8 }, { autoAlpha: 1, scale: 1, duration: 0.2, overwrite: true });

          lastScrollY = window.scrollY;
          index++;

          clearTimeout(fadeTimeout);
          fadeTimeout = setTimeout(() => images.forEach(img =>
            gsap.to(img, { autoAlpha: 0, scale: 0.2, duration: 0.8, ease: "expo.out" })
          ), 500);
        }
      }

      window.addEventListener("scroll", onScroll);

      return () => {
        window.removeEventListener("scroll", onScroll);
        clearTimeout(fadeTimeout);
        images.forEach(img => {
          gsap.killTweensOf(img);
          gsap.set(img, { autoAlpha: 0, scale: 1 });
        });
      };
    });

    return () => mm.revert();
  }, []);

  return (
    <section aria-label="About section" className="relative py-60">
      <div ref={wrapperRef} data-trail="wrapper" className="w-full h-full absolute inset-0 z-0">
        {media.map((item, i) => (
          <div key={i} data-trail="item" className="invisible rounded w-[15em] h-[20em] absolute overflow-hidden">
            <ImageOrVideo imageSrc={item.imageSrc} videoSrc={item.videoSrc} className="object-cover w-full h-full" />
          </div>
        ))}
      </div>
      <div className="relative z-10 flex flex-col items-center gap-2 w-content-width mx-auto text-center pointer-events-none">
        <h3 className="text-3xl md:text-5xl font-medium">{"About Us"}</h3>
        <TextAnimation
          text={"Welcome to Novera, where digital ambition meets precision."}
          variant={"fade-blur"}
          gradientText={true}
          tag="h2"
          className="text-7xl md:text-8xl leading-[1.15] font-semibold text-center text-balance"
        />
        <div className="flex flex-wrap justify-center gap-3 mt-2 md:mt-3 pointer-events-auto">
          <Button text={primaryButton.text} href={primaryButton.href} variant="primary" />
          <Button text={secondaryButton.text} href={secondaryButton.href} variant="secondary" />
        </div>
      </div>
    </section>
  );
};

export default function AboutSection() {
  return (
    <div 
      data-webild-section="about" 
      data-section="about" 
      id="about"
      className="[&_img]:rounded-[40%_60%_70%_30%_/_40%_50%_60%_50%] [&_img]:shadow-[0_0_40px_rgba(255,255,255,0.1)] [&_img]:transition-all [&_img]:duration-[3000ms] hover:[&_img]:rounded-[60%_40%_30%_70%_/_60%_30%_70%_40%] [&_img]:content-[url('https://images.unsplash.com/photo-1522071820081-009f0129c71c?auto=format&fit=crop&w=800&q=80')] [&_img]:object-cover"
    >
      <AboutInline />
    </div>
  );
}
