/* eslint-disable */
// @ts-nocheck — generated by catalog-eject; runtime-correct but TS strict-mode false-positives on inlined catalog body
import Button from "@/components/ui/Button";
import TextAnimation from "@/components/ui/TextAnimation";

interface AboutTextProps {
  title: string;
  primaryButton?: { text: string; href: string };
  secondaryButton?: { text: string; href: string };
  textAnimation: "slide-up" | "fade-blur" | "fade";
}

const AboutInline = () => {
  return (
    <section aria-label="About section" className="py-20">
      <div className="w-content-width mx-auto flex flex-col gap-2 items-center">
        <TextAnimation
          text={"About Us"}
          variant={"fade-blur"}
          gradientText={false}
          tag="h2"
          className="text-6xl 2xl:text-7xl leading-[1.15] font-semibold text-center text-balance"
        />

        {(undefined || undefined) && (
          <div className="flex flex-wrap gap-3 justify-center mt-2 md:mt-3">
            {undefined && <Button text={undefined.text} href={undefined.href} variant="primary" />}
            {undefined && <Button text={undefined.text} href={undefined.href} variant="secondary" animationDelay={0.1} />}
          </div>
        )}
      </div>
    </section>
  );
};

export default function AboutSection() {
  return (
    <div data-webild-section="about" data-section="about" id="about">
      <AboutInline />
    </div>
  );
}
