// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "faq" section.

import React from 'react';
import FaqSimple from '@/components/sections/faq/FaqSimple';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function FaqSection(): React.JSX.Element {
  return (
    <div id="faq" data-section="faq">
        <SectionErrorBoundary name="faq">
              <FaqSimple
          tag="Common Questions"
          title="Everything You Need to Know"
          description="Quick answers to help you understand our process."
          items={[
            {
              question: "How do you integrate AI?",
              answer: "We hand-pick the best AI models to complement human workflows, ensuring seamless operation.",
            },
            {
              question: "Is your work proprietary?",
              answer: "Every solution we deliver is custom-built for your specific brand requirements.",
            },
            {
              question: "How do I get started?",
              answer: "Schedule a discovery call, and we'll map out a solution tailored to your goals.",
            },
          ]}
          textAnimation="fade-blur"
        />
        </SectionErrorBoundary>
      </div>
  );
}
