// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "metrics" section.

import React from 'react';
import MetricsSimpleCards from '@/components/sections/metrics/MetricsSimpleCards';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function MetricsSection(): React.JSX.Element {
  return (
    <div id="metrics" data-section="metrics">
        <SectionErrorBoundary name="metrics">
              <MetricsSimpleCards
          tag="Impact Delivered"
          title="Measuring Success"
          description="Our solutions are designed to deliver measurable improvements to your business operations."
          metrics={[
            {
              value: "24/7",
              description: "Constant Engagement",
            },
            {
              value: "45%",
              description: "Efficiency Growth",
            },
            {
              value: "100+",
              description: "Projects Delivered",
            },
          ]}
          textAnimation="fade-blur"
        />
        </SectionErrorBoundary>
      </div>
  );
}
