// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "pricing" section.

import React from 'react';
import FeaturesRevealCardsBento from '@/components/sections/features/FeaturesRevealCardsBento';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function PricingSection(): React.JSX.Element {
  return (
    <div id="pricing" data-section="pricing">
        <SectionErrorBoundary name="pricing">
              <FeaturesRevealCardsBento
          tag="Our Portfolio"
          title="Crafting Excellence"
          description="Every solution we create is unique, leveraging modern AI to push the boundaries of what is possible."
          items={[
            {
              title: "AI-Enhanced UI",
              description: "Adaptive interfaces.",
              href: "#",
              imageSrc: "http://img.b2bpic.net/free-photo/3d-rendering-holographic-cube_23-2150979689.jpg",
            },
            {
              title: "Automated Scheduling",
              description: "Seamless bookings.",
              href: "#",
              imageSrc: "http://img.b2bpic.net/free-photo/structure-social-media-with-colored-icons_1134-73.jpg",
            },
            {
              title: "Custom Analytics",
              description: "Data-driven insights.",
              href: "#",
              imageSrc: "http://img.b2bpic.net/free-photo/augmented-reality-engineer-examining-holographic-machine_23-2152006121.jpg",
            },
            {
              title: "Integrated CRM",
              description: "Unified communications.",
              href: "#",
              imageSrc: "http://img.b2bpic.net/free-photo/global-network-illustration_53876-16141.jpg",
            },
            {
              title: "Voice Assistant",
              description: "Natural interactions.",
              href: "#",
              imageSrc: "http://img.b2bpic.net/free-photo/dark-phone-16-pro-max_187299-45925.jpg",
            },
            {
              title: "Security Protocols",
              description: "Enterprise-grade safety.",
              href: "#",
              imageSrc: "http://img.b2bpic.net/free-photo/man-holding-tablet-with-lighting-control-application-turning-lights-sitting-kitchen-house_482257-2744.jpg",
            },
            {
              title: "Cloud Scale",
              description: "Growth-ready infrastructure.",
              href: "#",
              imageSrc: "http://img.b2bpic.net/free-photo/cybersecurity-data-protection-concept_23-2152004114.jpg",
            },
          ]}
          textAnimation="fade-blur"
        />
        </SectionErrorBoundary>
      </div>
  );
}
